/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_xpenatan_imgui_ImGuiLayoutNative */

#ifndef _Included_com_github_xpenatan_imgui_ImGuiLayoutNative
#define _Included_com_github_xpenatan_imgui_ImGuiLayoutNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    ShowLayoutDebug
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_ShowLayoutDebug
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginLayout
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginLayout__Ljava_lang_String_2FF
  (JNIEnv *, jclass, jstring, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginLayout
 * Signature: (Ljava/lang/String;FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginLayout__Ljava_lang_String_2FFFFFF
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    EndLayout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_EndLayout
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginCollapseLayoutEx2
 * Signature: (Ljava/lang/String;FFLcom/github/xpenatan/imgui/ImGuiLayoutNative/ImGuiCollapseLayoutOptions;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginCollapseLayoutEx2
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jobject);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginCollapseLayoutEx
 * Signature: ([ZLjava/lang/String;FFLcom/github/xpenatan/imgui/ImGuiLayoutNative/ImGuiCollapseLayoutOptions;)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginCollapseLayoutEx
  (JNIEnv *, jclass, jbooleanArray, jstring, jfloat, jfloat, jobject);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginCollapseLayout2
 * Signature: (Ljava/lang/String;FFLcom/github/xpenatan/imgui/ImGuiLayoutNative/ImGuiCollapseLayoutOptions;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginCollapseLayout2
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jobject);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginCollapseLayout
 * Signature: ([ZLjava/lang/String;FFLcom/github/xpenatan/imgui/ImGuiLayoutNative/ImGuiCollapseLayoutOptions;)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginCollapseLayout
  (JNIEnv *, jclass, jbooleanArray, jstring, jfloat, jfloat, jobject);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    EndCollapseFrameLayout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_EndCollapseFrameLayout
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    EndCollapseLayout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_EndCollapseLayout
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginAlign
 * Signature: (Ljava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginAlign__Ljava_lang_String_2FFFF
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    BeginAlign
 * Signature: (Ljava/lang/String;FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_BeginAlign__Ljava_lang_String_2FFFFFF
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    EndAlign
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_EndAlign
  (JNIEnv *, jclass);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    AlignLayout
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_AlignLayout__FF
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    AlignLayout
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_AlignLayout__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_github_xpenatan_imgui_ImGuiLayoutNative
 * Method:    GetCurrentLayout
 * Signature: (Lcom/github/xpenatan/imgui/ImGuiLayoutNative/ImGuiLayout;)V
 */
JNIEXPORT void JNICALL Java_com_github_xpenatan_imgui_ImGuiLayoutNative_GetCurrentLayout
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiLayout */

#ifndef _Included_com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiLayout
#define _Included_com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiLayout
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiCollapseLayoutOptions */

#ifndef _Included_com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiCollapseLayoutOptions
#define _Included_com_github_xpenatan_imgui_ImGuiLayoutNative_ImGuiCollapseLayoutOptions
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
