
interface ImLayout {
//    void Begin([Const] DOMString name);
//    void End();

    static void DrawBoundingBox(float x1, float y1, float x2, float y2, long r, long g, long b, optional long a, optional boolean clipping);
};