
[NoDelete, Prefix="ImGuiWrapper::"]
interface ImGuiInternal {
    // Note: method overloading don't work with emscripten so we use _2, _3 and so on

    static long                    ImHashData_1([Const] DOMString data, long data_size, optional long seed);
    static long                    ImHashStr_1([Const] DOMString data, optional long data_size, optional long seed);

    static ImGuiWindow             GetCurrentWindow();
    static ImGuiWindow             FindWindowByID(long id);
    static ImGuiWindow             FindWindowByName([Const] DOMString name);

    // Windows: Display Order and Focus Order
    static void                    FocusWindow(ImGuiWindow window, optional ImGuiFocusRequestFlags ImGuiFocusRequestFlags);

    // Basic Helpers for widget code
    static void                    ItemSize([Const, Ref] ImVec2 size, optional float text_baseline_y);
    static void                    ItemSize_2([Const, Ref] ImRect bb, optional float text_baseline_y);
    static boolean                 ItemAdd([Const, Ref] ImRect bb, long id, [Const] optional ImRect nav_bb, optional ImGuiItemFlags ImGuiItemFlags);
    static boolean                 ItemHoverable([Const, Ref] ImRect bb, long id, ImGuiItemFlags ImGuiItemFlags);
    static boolean                 IsWindowContentHoverable(ImGuiWindow window, optional ImGuiHoveredFlags ImGuiHoveredFlags);
    static boolean                 IsClippedEx([Const, Ref] ImRect bb, long id);
    static void                    SetLastItemData(long item_id, ImGuiItemFlags ImGuiItemFlags, ImGuiItemStatusFlags ImGuiItemStatusFlags, [Const, Ref] ImRect item_rect);
    [Value] static ImVec2          CalcItemSize([Ref] ImVec2 size, float default_w, float default_h);
    static float                   CalcWrapWidthForPos([Const, Ref] ImVec2 pos, float wrap_pos_x);
    static void                    PushMultiItemsWidths(long components, float width_full);
    static boolean                 IsItemToggledSelection();
    [Value] static ImVec2          GetContentRegionMaxAbs();
    static void                    ShrinkWidths(ImGuiShrinkWidthItem items, long count, float width_excess);

    // Parameter stacks (shared)
    static void                    PushItemFlag(ImGuiItemFlags ImGuiItemFlags, boolean enabled);
    static void                    PopItemFlag();

    static void                    DockBuilderDockWindow([Const] DOMString window_name, long node_id);
    static ImGuiDockNode           DockBuilderGetNode(long node_id);
    static ImGuiDockNode           DockBuilderGetCentralNode(long node_id);
    static long                    DockBuilderAddNode(optional long node_id, optional ImGuiDockNodeFlags ImGuiDockNodeFlags);
    static void                    DockBuilderRemoveNode(long node_id);
    static void                    DockBuilderRemoveNodeDockedWindows(long node_id, optional boolean clear_settings_refs);
    static void                    DockBuilderRemoveNodeChildNodes(long node_id);
    static void                    DockBuilderSetNodePos(long node_id, [Ref] ImVec2 pos);
    static void                    DockBuilderSetNodeSize(long node_id, [Ref] ImVec2 size);
    static long                    DockBuilderSplitNode(long node_id, ImGuiDir split_dir, float size_ratio_for_node_at_dir, long[] out_id_at_dir, long[] out_id_at_opposite_dir);
//    static void                    DockBuilderCopyDockSpace(long src_dockspace_id, long dst_dockspace_id, ImVector<const char*>* in_window_remap_pairs);
//    static void                    DockBuilderCopyNode(long src_node_id, long dst_node_id, ImVector<long>* out_node_remap_pairs);
    static void                    DockBuilderCopyWindowSettings([Const] DOMString src_name, [Const] DOMString dst_name);
    static void                    DockBuilderFinish(long node_id);

    static boolean                 BeginTableEx([Const] DOMString str_id, long id, long column, optional ImGuiTableFlags ImGuiTableFlags, [Const, Ref] optional ImVec2 outer_size, optional float inner_width);

    static ImGuiTabBar             GetCurrentTabBar();
    static ImGuiTabItem            TabBarFindTabByID(ImGuiTabBar tab_bar, long tab_id);
    static ImGuiTabItem            TabBarFindTabByOrder(ImGuiTabBar tab_bar, long order);
    static void                    TabBarCloseTab(ImGuiTabBar tab_bar, ImGuiTabItem tab);
    static void                    TabBarQueueFocus(ImGuiTabBar tab_bar, ImGuiTabItem tab);
    static void                    TabBarQueueReorder(ImGuiTabBar tab_bar, ImGuiTabItem tab, long offset);

    // Basic Accessors
    static long                    GetActiveID();
    static long                    GetFocusID();
    static void                    SetActiveID(long id, ImGuiWindow window);
    static void                    SetFocusID(long id, ImGuiWindow window);
    static void                    ClearActiveID();

    // Render helpers (those functions don't access any ImGui state!)
    static void                    RenderArrow(ImDrawList draw_list, [Ref] ImVec2 pos, long col, ImGuiDir dir, optional float scale);
    static void                    RenderBullet(ImDrawList draw_list, [Ref] ImVec2 pos, long col);
    static void                    RenderCheckMark(ImDrawList draw_list, [Ref] ImVec2 pos, long col, float sz);
    static void                    RenderArrowPointingAt(ImDrawList draw_list, [Ref] ImVec2 pos, [Ref] ImVec2 half_sz, ImGuiDir direction, long col);
    static void                    RenderArrowDockMenu(ImDrawList draw_list, [Ref] ImVec2 p_min, float sz, long col);
    static void                    RenderRectFilledRangeH(ImDrawList draw_list, [Const, Ref] ImRect rect, long col, float x_start_norm, float x_end_norm, float rounding);
    static void                    RenderRectFilledWithHole(ImDrawList draw_list, [Const, Ref] ImRect outer, [Const, Ref] ImRect inner, long col, float rounding);
    static ImDrawFlags             CalcRoundingFlagsForRectInRect([Const, Ref] ImRect r_in, [Const, Ref] ImRect r_outer, float threshold);

    // Widgets
//    static void                    TextEx(const char* text, const char* text_end = NULL, ImGuiTextFlags flags = 0);
//    static boolean                 ButtonEx(const char* label, const ImVec2& size_arg = ImVec2(0, 0), ImGuiButtonFlags flags = 0);
    static boolean                 ArrowButtonEx([Const] DOMString str_id, ImGuiDir dir, [Ref] ImVec2 size_arg, optional ImGuiButtonFlags ImGuiButtonFlags);
//    static boolean                 ImageButtonEx(long id, ImTextureID texture_id, const ImVec2& image_size, const ImVec2& uv0, const ImVec2& uv1, const ImVec4& bg_col, const ImVec4& tint_col, ImGuiButtonFlags flags = 0);
//    static void                    SeparatorEx(ImGuiSeparatorFlags flags, float thickness = 1.0f);
//    static void                    SeparatorTextEx(long id, const char* label, const char* label_end, float extra_width);
//    static boolean                 CheckboxFlags(const char* label, ImS64* flags, ImS64 flags_value);
//    static boolean                 CheckboxFlags(const char* label, ImU64* flags, ImU64 flags_value);

    // Widgets low-level behaviors
    static boolean                 ButtonBehavior([Const, Ref] ImRect bb, long id, boolean[] out_hovered, boolean[] out_held, optional ImGuiButtonFlags ImGuiButtonFlags);
    static boolean                 DragBehavior(long id, ImGuiDataType ImGuiDataType, any p_v, float v_speed, [Const] any p_min, [Const] any p_max, [Const] DOMString format, ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderBehavior([Const, Ref] ImRect bb, long id, ImGuiDataType ImGuiDataType, any p_v, [Const] any p_min, [Const] any p_max, [Const] DOMString format, ImGuiSliderFlags ImGuiSliderFlags, ImRect out_grab_bb);
    static boolean                 SplitterBehavior([Const, Ref] ImRect bb, long id, ImGuiAxis axis, float[] size1, float[] size2, float min_size1, float min_size2, optional float hover_extend, optional float hover_visibility_delay, optional long bg_col);
    static boolean                 TreeNodeBehavior(long id, ImGuiTreeNodeFlags ImGuiTreeNodeFlags, [Const] DOMString label, [Const] optional DOMString label_end);
    static void                    TreePushOverrideID(long id);
    static void                    TreeNodeSetOpen(long id, boolean open);
    static boolean                 TreeNodeUpdateNextOpen(long id, ImGuiTreeNodeFlags ImGuiTreeNodeFlags);
    static void                    SetNextItemSelectionUserData(long selection_user_data);
};

[NoDelete, Prefix="ImGuiWrapper::"]
interface ImGui {
    // Note: method overloading don't work with emscripten so we use _2, _3 and so on

    static ImGuiContext            CreateContext();
    static void                    DestroyContext(optional ImGuiContext ctx);
    static ImGuiContext            GetCurrentContext();
    static void                    SetCurrentContext(ImGuiContext ctx);

    [Ref] static ImGuiIO           GetIO();
    [Ref] static ImGuiStyle        GetStyle();
    static void                    NewFrame();
    static void                    EndFrame();
    static void                    Render();
    static ImDrawData              GetDrawData();

    static void                    ShowDemoWindow(optional boolean[] p_open);
    static void                    ShowMetricsWindow(optional boolean[] p_open);
    static void                    ShowDebugLogWindow(optional boolean[] p_open);
    static void                    ShowAboutWindow(optional boolean[] p_open);
    static void                    ShowStyleEditor(optional ImGuiStyle ref);
    static void                    ShowStyleSelector([Const] DOMString label);
    static void                    ShowFontSelector([Const] DOMString label);
    static void                    ShowUserGuide();
////    [Const] DOMString        GetVersion();

    static void                    StyleColorsDark(optional ImGuiStyle dst);
    static void                    StyleColorsLight(optional ImGuiStyle dst);
    static void                    StyleColorsClassic(optional ImGuiStyle dst);

    static boolean                 Begin([Const] DOMString name, optional boolean[] p_open, optional ImGuiWindowFlags ImGuiWindowFlags);
    static void                    End();

    static boolean                 BeginChild([Const] DOMString str_id, [Const,Ref] optional ImVec2 size, optional ImGuiChildFlags ImGuiChildFlags, optional ImGuiWindowFlags ImGuiWindowFlags);
    static boolean                 BeginChild_2(long id, [Const,Ref] optional ImVec2 size, optional ImGuiChildFlags ImGuiChildFlags, optional ImGuiWindowFlags ImGuiWindowFlags);
    static void                    EndChild();

    static boolean                 IsWindowAppearing();
    static boolean                 IsWindowCollapsed();
    static boolean                 IsWindowFocused(optional ImGuiFocusedFlags ImGuiFocusedFlags);
    static boolean                 IsWindowHovered(optional ImGuiFocusedFlags ImGuiFocusedFlags);
    static ImDrawList              GetWindowDrawList();
    static float                   GetWindowDpiScale();
    [Value] static ImVec2          GetWindowPos();
    [Value] static ImVec2          GetWindowSize();
    static float                   GetWindowWidth();
    static float                   GetWindowHeight();
    static ImGuiViewport           GetWindowViewport();

    static void                    SetNextWindowPos([Const, Ref]ImVec2 pos, optional ImGuiCond ImGuiCond, [Const, Ref] optional ImVec2 pivot);
    static void                    SetNextWindowSize([Const, Ref]ImVec2 size, optional ImGuiCond ImGuiCond);
    static void                    SetNextWindowSizeConstraints([Const, Ref]ImVec2 size_min, [Const, Ref]ImVec2 size_max); //, optional CustomImGuiSizeCallback custom_callback, any custom_callback_data);
    static void                    SetNextWindowContentSize([Const, Ref]ImVec2 size);
    static void                    SetNextWindowCollapsed(boolean collapsed, optional ImGuiCond ImGuiCond);
    static void                    SetNextWindowFocus();
    static void                    SetNextWindowScroll([Const, Ref]ImVec2 scroll);
    static void                    SetNextWindowBgAlpha(float alpha);
    static void                    SetNextWindowViewport(long viewport_id);
    static void                    SetWindowPos([Const, Ref]ImVec2 pos, optional ImGuiCond ImGuiCond);
    static void                    SetWindowSize([Const, Ref]ImVec2 size, optional ImGuiCond ImGuiCond);
    static void                    SetWindowCollapsed(boolean collapsed, optional ImGuiCond ImGuiCond);
    static void                    SetWindowFocus();
    static void                    SetWindowFontScale(float scale);
    static void                    SetWindowPos_2([Const] DOMString name, [Const, Ref]ImVec2 pos, optional ImGuiCond ImGuiCond);
    static void                    SetWindowSize_2([Const] DOMString name, [Const, Ref]ImVec2 size, optional ImGuiCond ImGuiCond);
    static void                    SetWindowCollapsed_2([Const] DOMString name, boolean collapsed, optional ImGuiCond ImGuiCond);
    static void                    SetWindowFocus([Const] DOMString name);

    [Value] static ImVec2          GetContentRegionAvail();
    [Value] static ImVec2          GetContentRegionMax();
    [Value] static ImVec2          GetWindowContentRegionMin();
    [Value] static ImVec2          GetWindowContentRegionMax();

    static float                   GetScrollX();
    static float                   GetScrollY();
    static void                    SetScrollX(float scroll_x);
    static void                    SetScrollY(float scroll_y);
    static float                   GetScrollMaxX();
    static float                   GetScrollMaxY();
    static void                    SetScrollHereX(optional float center_x_ratio);
    static void                    SetScrollHereY(optional float center_y_ratio);
    static void                    SetScrollFromPosX(float local_x, optional float center_x_ratio);
    static void                    SetScrollFromPosY(float local_y, optional float center_y_ratio);

    static void                    PushFont(ImFont font);
    static void                    PopFont();
    static void                    PushStyleColor(ImGuiCol idx, unsigned long col);
    static void                    PushStyleColor_2(ImGuiCol idx, [Const, Ref] ImVec4 col);
    static void                    PopStyleColor(optional long count);
    static void                    PushStyleVar(ImGuiStyleVar idx, float val);
    static void                    PushStyleVar_2(ImGuiStyleVar idx, [Const, Ref]ImVec2 val);
    static void                    PopStyleVar(optional long count);
    static void                    PushTabStop(boolean tab_stop);
    static void                    PopTabStop();
    static void                    PushButtonRepeat(boolean repeat);
    static void                    PopButtonRepeat();

    static void                    PushItemWidth(float item_width);
    static void                    PopItemWidth();
    static void                    SetNextItemWidth(float item_width);
    static float                   CalcItemWidth();
    static void                    PushTextWrapPos(optional float wrap_local_pos_x);
    static void                    PopTextWrapPos();

    static ImFont                  GetFont();
    static float                   GetFontSize();
    [Value] static ImVec2          GetFontTexUvWhitePixel();
    static unsigned long           GetColorU32Style(long idx, optional float alpha_mul);
    static unsigned long           GetColorU32_2([Const, Ref]ImVec4 col);
    static unsigned long           GetColorU32_3(unsigned long col);
    [Const, Ref] static ImVec4     GetStyleColorVec4(long idx);

    static void                    Separator();
    static void                    SameLine(optional float offset_from_start_x, optional float spacing);
    static void                    NewLine();
    static void                    Spacing();
    static void                    Dummy([Const, Ref]ImVec2 size);
    static void                    Indent(optional float indent_w);
    static void                    Unindent(optional float indent_w);
    static void                    BeginGroup();
    static void                    EndGroup();
    [Value] static ImVec2          GetCursorPos();
    static float                   GetCursorPosX();
    static float                   GetCursorPosY();
    static void                    SetCursorPos([Const, Ref] ImVec2 local_pos);
    static void                    SetCursorPosX(float local_x);
    static void                    SetCursorPosY(float local_y);
    [Value] static ImVec2          GetCursorStartPos();
    [Value] static ImVec2          GetCursorScreenPos();
    static void                    SetCursorScreenPos([Const, Ref] ImVec2 pos);
    static void                    AlignTextToFramePadding();
    static float                   GetTextLineHeight();
    static float                   GetTextLineHeightWithSpacing();
    static float                   GetFrameHeight();
    static float                   GetFrameHeightWithSpacing();

    static void                    PushID([Const] DOMString str_id);
    static void                    PushID([Const] DOMString str_id_begin, [Const] DOMString str_id_end);
    static void                    PushID_2(long int_id);
//    static void                    PushID_3([Const] any ptr_id);
    static void                    PopID();
    static long                    GetID([Const] DOMString str_id);
    static long                    GetID_2([Const] DOMString str_id_begin, [Const] DOMString str_id_end);
    static long                    GetID_3([Const] any ptr_id);

    static void                    TextUnformatted([Const] DOMString text, [Const] optional DOMString text_end);
    static void                    Text([Const] DOMString fmt);
////    static void                    TextV([Const] DOMString fmt, DOMString args);
    static void                    TextColored([Const, Ref] ImVec4 col, [Const] DOMString fmt);
////    static void                    TextColoredV([Const, Ref] ImVec4 col, [Const] DOMString fmt, DOMString args);
    static void                    TextDisabled([Const] DOMString fmt);
////    static void                    TextDisabledV([Const] DOMString fmt, DOMString args);
    static void                    TextWrapped([Const] DOMString fmt);
////    static void                    TextWrappedV([Const] DOMString fmt, DOMString args);
    static void                    LabelText([Const] DOMString label, [Const] DOMString fmt);
////    static void                    LabelTextV([Const] DOMString label, [Const] DOMString fmt, DOMString args);
    static void                    BulletText([Const] DOMString fmt);
////    static void                    BulletTextV([Const] DOMString fmt, DOMString args);

    static boolean                 Button([Const] DOMString label, [Const, Ref] optional ImVec2 size);
    static boolean                 SmallButton([Const] DOMString label);
    static boolean                 InvisibleButton([Const] DOMString str_id, [Const, Ref] ImVec2 size, optional ImGuiButtonFlags ImGuiButtonFlags);
    static boolean                 ArrowButton([Const] DOMString str_id, ImGuiDir dir);
    static boolean                 Checkbox([Const] DOMString label, boolean[] v);
    static boolean                 CheckboxFlags([Const] DOMString label, long[] flags, long flags_value);
//    static boolean                 CheckboxFlags_2([Const] DOMString label, unsigned long[] flags, unsigned long flags_value);
    static boolean                 RadioButton([Const] DOMString label, boolean active);
    static boolean                 RadioButton_2([Const] DOMString label, long[] v, long v_button);
    static void                    ProgressBar(float fraction, [Const, Ref] optional ImVec2 size_arg, [Const] optional DOMString overlay);
    static void                    Bullet();

    static void                    Image(long user_texture_id, [Const, Ref] ImVec2 size, [Const, Ref] optional ImVec2 uv0, [Const, Ref] optional ImVec2 uv1, [Const, Ref] optional ImVec4 tint_col, [Const, Ref] optional ImVec4 border_col);
    static boolean                 ImageButton([Const] DOMString str_id, long user_texture_id, [Const, Ref] ImVec2 size, [Const, Ref] optional ImVec2 uv0, [Const, Ref] optional ImVec2 uv1, [Const, Ref] optional ImVec4 bg_col, [Const, Ref] optional ImVec4 tint_col);

    static boolean                 BeginCombo([Const] DOMString label, [Const] DOMString preview_value, optional ImGuiComboFlags ImGuiComboFlags);
    static void                    EndCombo();
////    boolean                 Combo([Const] DOMString label, long[] current_item, [Const] DOMString [Const]items[], long items_count, optional long popup_max_height_in_items);  // items with multiple [Const]???
    static boolean                 Combo([Const] DOMString label, long[] current_item, [Const] DOMString items_separated_by_zeros, optional long popup_max_height_in_items);
////    boolean                 Combo([Const] DOMString label, long[] current_item, boolean(*items_getter)(any data, long idx, [Const] DOMString* out_text), any data, long items_count, optional long popup_max_height_in_items); // crazy boolean with param

    static boolean                 DragFloat([Const] DOMString label, float[] v, optional float v_speed, optional float v_min, optional float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragFloat2([Const] DOMString label, float[] v, optional float v_speed, optional float v_min, optional float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragFloat3([Const] DOMString label, float[] v, optional float v_speed, optional float v_min, optional float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragFloat4([Const] DOMString label, float[] v, optional float v_speed, optional float v_min, optional float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragFloatRange2([Const] DOMString label, float[] v_current_min, float[] v_current_max, optional float v_speed, optional float v_min, optional float v_max, [Const] optional DOMString format, [Const] optional DOMString format_max, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragInt([Const] DOMString label, long[] v, optional float v_speed, optional long v_min, optional long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragInt2([Const] DOMString label, long[] v, optional float v_speed, optional long v_min, optional long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragInt3([Const] DOMString label, long[] v, optional float v_speed, optional long v_min, optional long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragInt4([Const] DOMString label, long[] v, optional float v_speed, optional long v_min, optional long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 DragIntRange2([Const] DOMString label, long[] v_current_min, long[] v_current_max, optional float v_speed, optional long v_min, optional long v_max, [Const] optional DOMString format, [Const] optional DOMString format_max, optional ImGuiSliderFlags ImGuiSliderFlags);
//    static boolean                 DragScalar([Const] DOMString label, long data_type, any p_data, optional float v_speed, [Const] optional any p_min, [Const] optional any p_max, [Const] optional DOMString format, optional ImGuiSliderFlags flags);
//    static boolean                 DragScalarN([Const] DOMString label, long data_type, any p_data, long components, optional float v_speed, [Const] optional any p_min, [Const] optional any p_max, [Const] optional DOMString format, optional ImGuiSliderFlags flags);

    static boolean                 SliderFloat([Const] DOMString label, float[] v, float v_min, float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderFloat2([Const] DOMString label, float[] v, float v_min, float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderFloat3([Const] DOMString label, float[] v, float v_min, float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderFloat4([Const] DOMString label, float[] v, float v_min, float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderAngle([Const] DOMString label, float[] v_rad, optional float v_degrees_min, optional float v_degrees_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderInt([Const] DOMString label, long[] v, long v_min, long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderInt2([Const] DOMString label, long[] v, long v_min, long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderInt3([Const] DOMString label, long[] v, long v_min, long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 SliderInt4([Const] DOMString label, long[] v, long v_min, long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
//    static boolean                 SliderScalar([Const] DOMString label, long data_type, any p_data, [Const] any p_min, [Const] any p_max, [Const] optional DOMString format, optional ImGuiSliderFlags flags);
//    static boolean                 SliderScalarN([Const] DOMString label, long data_type, any p_data, long components, [Const] any p_min, [Const] any p_max, [Const] optional DOMString format, optional ImGuiSliderFlags flags);
    static boolean                 VSliderFloat([Const] DOMString label, [Const, Ref] ImVec2 size, float[] v, float v_min, float v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
    static boolean                 VSliderInt([Const] DOMString label, [Const, Ref] ImVec2 size, long[] v, long v_min, long v_max, [Const] optional DOMString format, optional ImGuiSliderFlags ImGuiSliderFlags);
//    static boolean                 VSliderScalar([Const] DOMString label, [Const, Ref] ImVec2 size, long data_type, any p_data, [Const] any p_min, [Const] any p_max, [Const] optional DOMString format, optional ImGuiSliderFlags flags);

    static boolean                 InputText([Const] DOMString label, byte[] buf, long long buf_size, optional ImGuiInputTextFlags ImGuiInputTextFlags); //, optional ImGuiInputTextCallback callback, optional ImGuiInputTextFlags flags);
    static boolean                 InputTextMultiline([Const] DOMString label, byte[] buf, long long buf_size, [Const, Ref] optional ImVec2 size, optional ImGuiInputTextFlags ImGuiInputTextFlags); //, optional ImGuiInputTextCallback callback, optional any user_data);
    static boolean                 InputTextWithHint([Const] DOMString label, [Const] DOMString hint, byte[] buf, long long buf_size, optional ImGuiInputTextFlags ImGuiInputTextFlags); //, optional ImGuiInputTextCallback callback, optional any user_data);
    static boolean                 InputFloat([Const] DOMString label, float[] v, optional float step, optional float step_fast, [Const] optional DOMString format, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputFloat2([Const] DOMString label, float[] v, [Const] optional DOMString format, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputFloat3([Const] DOMString label, float[] v, [Const] optional DOMString format, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputFloat4([Const] DOMString label, float[] v, [Const] optional DOMString format, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputInt([Const] DOMString label, long[] v, optional long step, optional long step_fast, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputInt2([Const] DOMString label, long[] v, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputInt3([Const] DOMString label, long[] v, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputInt4([Const] DOMString label, long[] v, optional ImGuiInputTextFlags ImGuiInputTextFlags);
    static boolean                 InputDouble([Const] DOMString label, double[] v, optional double step, optional double step_fast, [Const] optional DOMString format, optional ImGuiInputTextFlags ImGuiInputTextFlags);
//    static boolean                 InputScalar([Const] DOMString label, long data_type, any p_data, [Const] optional any p_step, [Const] optional any p_step_fast, [Const] optional DOMString format, optional ImGuiInputTextFlags flags);
//    static boolean                 InputScalarN([Const] DOMString label, long data_type, any p_data, long components, [Const] optional any p_step, [Const] optional any p_step_fast, [Const] optional DOMString format, optional ImGuiInputTextFlags flags);
//
    static boolean                 ColorEdit3([Const] DOMString label, float[] col, optional ImGuiColorEditFlags ImGuiColorEditFlags);
    static boolean                 ColorEdit4([Const] DOMString label, float[] col, optional ImGuiColorEditFlags ImGuiColorEditFlags);
    static boolean                 ColorPicker3([Const] DOMString label, float[] col, optional ImGuiColorEditFlags ImGuiColorEditFlags);
    static boolean                 ColorPicker4([Const] DOMString label, float[] col, optional ImGuiColorEditFlags ImGuiColorEditFlags, [Const] optional float[] ref_col);
    static boolean                 ColorButton([Const] DOMString desc_id, [Const, Ref] ImVec4 col, optional ImGuiColorEditFlags ImGuiColorEditFlags, [Const, Ref] optional ImVec2 size);
    static void                    SetColorEditOptions(ImGuiColorEditFlags ImGuiColorEditFlags);

    static boolean                 TreeNode([Const] DOMString label);
    static boolean                 TreeNode_2([Const] DOMString str_id, [Const] DOMString fmt);
    static boolean                 TreeNode_3([Const] any ptr_id, [Const] DOMString fmt);
////    static boolean                 TreeNodeV([Const] DOMString str_id, [Const] DOMString fmt, DOMString args);
////    static boolean                 TreeNodeV_2([Const] any ptr_id, [Const] DOMString fmt, DOMString args);
    static boolean                 TreeNodeEx([Const] DOMString label, optional ImGuiTreeNodeFlags flaImGuiTreeNodeFlagsgs);
    static boolean                 TreeNodeEx_2([Const] DOMString str_id, ImGuiTreeNodeFlags ImGuiTreeNodeFlags, [Const] DOMString fmt);
    static boolean                 TreeNodeEx_3([Const] any ptr_id, ImGuiTreeNodeFlags ImGuiTreeNodeFlags, [Const] DOMString fmt);
////    static boolean                 TreeNodeExV([Const] DOMString str_id, ImGuiTreeNodeFlags flags, [Const] DOMString fmt, DOMString args);
////    static boolean                 TreeNodeExV_2([Const] any ptr_id, ImGuiTreeNodeFlags flags, [Const] DOMString fmt, DOMString args);
    static void                    TreePush([Const] DOMString str_id);
//    static void                    TreePush_2([Const] any ptr_id);
    static void                    TreePop();
    static float                   GetTreeNodeToLabelSpacing();
    static boolean                 CollapsingHeader([Const] DOMString label, optional ImGuiTreeNodeFlags ImGuiTreeNodeFlags);
    static boolean                 CollapsingHeader_2([Const] DOMString label, boolean[] p_visible, optional ImGuiTreeNodeFlags ImGuiTreeNodeFlags);
    static void                    SetNextItemOpen(boolean is_open, optional ImGuiCond ImGuiCond);

    static boolean                 Selectable([Const] DOMString label, optional boolean selected, optional ImGuiSelectableFlags flags, [Const, Ref] optional ImVec2 size);
    static boolean                 Selectable_2([Const] DOMString label, boolean[] p_selected, optional ImGuiSelectableFlags flags, [Const, Ref] optional ImVec2 size);

    static boolean                 BeginListBox([Const] DOMString label, [Const, Ref] optional ImVec2 size);
    static void                    EndListBox();
////    boolean                 ListBox([Const] DOMString label, long[] current_item, [Const] DOMString[] items, long items_count, optional long height_in_items);
////    boolean                 ListBox([Const] DOMString label, long[] current_item, boolean (*items_getter)(any data, long idx, [Const] DOMString[] out_text), any data, long items_count, optional long height_in_items);
//
    static void                    PlotLines([Const] DOMString label, [Const]float[] values, long values_count, optional long values_offset, [Const] optional DOMString overlay_text, optional float scale_min, optional float scale_max); //, [Value] optional ImVec2 graph_size, optional long stride); //ERROR graph size
////    void                    PlotLines([Const] DOMString label, float(*values_getter)(any data, long idx), any data, long values_count, optional long values_offset, [Const] optional DOMString overlay_text, optional float scale_min, optional float scale_max, [Value] optionalImVec2 graph_size);
    static void                    PlotHistogram([Const] DOMString label, [Const]float[] values, long values_count, optional long values_offset, [Const] optional DOMString overlay_text, optional float scale_min, optional float scale_max);//, [Value] optional ImVec2 graph_size, optional long stride); //ERROR graph size
////    void                    PlotHistogram([Const] DOMString label, float(*values_getter)(any data, long idx), any data, long values_count, optional long values_offset, [Const] optional DOMString overlay_text, optional float scale_min, optional float scale_max, [Value] optional ImVec2 graph_size);

    static void                    Value([Const] DOMString prefix, boolean b);
    static void                    Value_2([Const] DOMString prefix, long v);
    static void                    Value_4([Const] DOMString prefix, float v, [Const] optional DOMString float_format);

    static boolean                 BeginMenuBar();
    static void                    EndMenuBar();
    static boolean                 BeginMainMenuBar();
    static void                    EndMainMenuBar();
    static boolean                 BeginMenu([Const] DOMString label, optional boolean enabled);
    static void                    EndMenu();
    static boolean                 MenuItem([Const] DOMString label, [Const] optional DOMString shortcut, optional boolean selected, optional boolean enabled);
    static boolean                 MenuItem_2([Const] DOMString label, [Const] DOMString shortcut, boolean[] p_selected, optional boolean enabled);
//
    static void                    BeginTooltip();
    static void                    EndTooltip();
    static void                    SetTooltip([Const] DOMString fmt);
////    static void                    SetTooltipV([Const] DOMString fmt, DOMString args);

    static boolean                 BeginItemTooltip();
    static void                    SetItemTooltip([Const] DOMString fmt);

    static boolean                 BeginPopup([Const] DOMString str_id, optional ImGuiWindowFlags ImGuiWindowFlags);
    static boolean                 BeginPopupModal([Const] DOMString name, optional boolean[] p_open, optional ImGuiWindowFlags ImGuiWindowFlags);
    static boolean                 BeginPopupModal2([Const] DOMString name, ImGuiWindowFlags ImGuiWindowFlags);
    static void                    EndPopup();
//
    static void                    OpenPopup([Const] DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
    static void                    OpenPopup_2(long id, optional ImGuiPopupFlags ImGuiPopupFlags);
    static void                    OpenPopupOnItemClick([Const] optional DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
    static void                    CloseCurrentPopup();
//
    static boolean                 BeginPopupContextItem([Const] optional DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
    static boolean                 BeginPopupContextWindow([Const] optional DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
    static boolean                 BeginPopupContextVoid([Const] optional DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
//
    static boolean                 IsPopupOpen([Const] DOMString str_id, optional ImGuiPopupFlags ImGuiPopupFlags);
//
    static boolean                 BeginTable([Const] DOMString str_id, long column, optional ImGuiTableFlags ImGuiTableFlags, [Const, Ref] optional ImVec2 outer_size, optional float inner_width);
    static void                    EndTable();
    static void                    TableNextRow(optional long row_flags, optional float min_row_height);
    static boolean                 TableNextColumn();
    static boolean                 TableSetColumnIndex(long column_n);

    static void                    TableSetupColumn([Const] DOMString label, optional ImGuiTableColumnFlags ImGuiTableColumnFlags, optional float init_width_or_weight, optional long user_id);
    static void                    TableSetupScrollFreeze(long cols, long rows);
    static void                    TableHeadersRow();
    static void                    TableHeader([Const] DOMString label);

    static ImGuiTableSortSpecs     TableGetSortSpecs();
    static long                    TableGetColumnCount();
    static long                    TableGetColumnIndex();
    static long                    TableGetRowIndex();
//    [Const] DOMString        TableGetColumnName(optional long column_n);
    static long                    TableGetColumnFlags(optional long column_n);
    static void                    TableSetColumnEnabled(long column_n, boolean v);
    static void                    TableSetBgColor(long target, unsigned long color, optional long column_n);

    static void                    Columns(optional long count, [Const] optional DOMString id, optional boolean border);
    static void                    NextColumn();
    static long                    GetColumnIndex();
    static float                   GetColumnWidth(optional long column_index);
    static void                    SetColumnWidth(long column_index, float width);
    static float                   GetColumnOffset(optional long column_index);
    static void                    SetColumnOffset(long column_index, float offset_x);
    static long                    GetColumnsCount();

    static boolean                 BeginTabBar([Const] DOMString str_id, optional ImGuiTabBarFlags ImGuiTabBarFlags);
    static void                    EndTabBar();
    static boolean                 BeginTabItem([Const] DOMString label, optional boolean[] p_open, optional ImGuiTabItemFlags ImGuiTabItemFlags);
    static void                    EndTabItem();
    static boolean                 TabItemButton([Const] DOMString label, ImGuiTabItemFlags ImGuiTabItemFlags);
    static void                    SetTabItemClosed([Const] DOMString tab_or_docked_window_label);

    static long                    DockSpace(long id, [Const, Ref] optional ImVec2 size, optional ImGuiDockNodeFlags ImGuiDockNodeFlags, [Const] optional ImGuiWindowClass window_class);
    static long                    DockSpaceOverViewport([Const] optional ImGuiViewport viewport, optional ImGuiDockNodeFlags ImGuiDockNodeFlags, [Const] optional ImGuiWindowClass window_class);
    static void                    SetNextWindowDockID(long dock_id, optional ImGuiCond ImGuiCond);
    static void                    SetNextWindowClass([Const]ImGuiWindowClass window_class);
    static long                    GetWindowDockID();
    static boolean                 IsWindowDocked();

//    static void                    LogToTTY(optional long auto_open_depth);
//    static void                    LogToFile(optional long auto_open_depth, [Const] optional DOMString filename);
//    static void                    LogToClipboard(optional long auto_open_depth);
//    static void                    LogFinish();
//    static void                    LogButtons();
//    static void                    LogText([Const] DOMString fmt);
////    static void                    LogTextV([Const] DOMString fmt, DOMString args);

    static boolean                 BeginDragDropSource(optional ImGuiDragDropFlags ImGuiDragDropFlags);
    static boolean                 SetDragDropPayload([Const] DOMString type, long data, optional ImGuiCond ImGuiCond);
    static void                    EndDragDropSource();
    static boolean                 BeginDragDropTarget();
    [Const] static ImGuiPayload    AcceptDragDropPayload([Const] DOMString type, optional ImGuiDragDropFlags ImGuiDragDropFlags);
    static void                    EndDragDropTarget();
    [Const] static ImGuiPayload    GetDragDropPayload();

    static void                    BeginDisabled(optional boolean disabled);
    static void                    EndDisabled();

    static void                    PushClipRect([Const, Ref]ImVec2 clip_rect_min, [Const, Ref]ImVec2 clip_rect_max, boolean intersect_with_current_clip_rect);
    static void                    PopClipRect();

    static void                    SetItemDefaultFocus();
    static void                    SetKeyboardFocusHere(optional long offset);

    static void                    SetNextItemAllowOverlap();

    static boolean                 IsItemHovered(optional ImGuiHoveredFlags ImGuiHoveredFlags);
    static boolean                 IsItemActive();
    static boolean                 IsItemFocused();
    static boolean                 IsItemClicked(optional ImGuiMouseButton ImGuiMouseButton);
    static boolean                 IsItemVisible();
    static boolean                 IsItemEdited();
    static boolean                 IsItemActivated();
    static boolean                 IsItemDeactivated();
    static boolean                 IsItemDeactivatedAfterEdit();
    static boolean                 IsItemToggledOpen();
    static boolean                 IsAnyItemHovered();
    static boolean                 IsAnyItemActive();
    static boolean                 IsAnyItemFocused();
    static long                    GetItemID();
    [Value] static ImVec2          GetItemRectMin();
    [Value] static ImVec2          GetItemRectMax();
    [Value] static ImVec2          GetItemRectSize();

    static ImGuiViewport           GetMainViewport();

    static ImDrawList              GetBackgroundDrawList();
    static ImDrawList              GetForegroundDrawList();
    static ImDrawList              GetBackgroundDrawList_2(ImGuiViewport viewport);
    static ImDrawList              GetForegroundDrawList_2(ImGuiViewport viewport);

    static boolean                 IsRectVisible([Const, Ref]ImVec2 size);
    static boolean                 IsRectVisible_2([Const, Ref]ImVec2 rect_min, [Const, Ref]ImVec2 rect_max);
    static double                  GetTime();
    static long                    GetFrameCount();
    static ImDrawListSharedData    GetDrawListSharedData();
////    [Const] DOMString        GetStyleColorName(long idx);
    static void                    SetStateStorage(ImGuiStorage storage);
    static ImGuiStorage            GetStateStorage();

    [Value] static ImVec2          CalcTextSize([Const] DOMString text, [Const] optional DOMString text_end, optional boolean hide_text_after_double_hash, optional float wrap_width);
//
    [Value] static ImVec4          ColorConvertU32ToFloat4(unsigned long col);
    static unsigned long           ColorConvertFloat4ToU32([Const, Ref]ImVec4 col);
    static void                    ColorConvertRGBtoHSV(float r, float g, float b, float[] out_h, float[] out_s, float[] out_v); // fix by changing to pointer
    static void                    ColorConvertHSVtoRGB(float h, float s, float v, float[] out_r, float[] out_g, float[] out_b); // fix by changing to pointer

    static boolean                 IsKeyDown(ImGuiKey key);
    static boolean                 IsKeyPressed(ImGuiKey key, optional boolean repeat);
    static boolean                 IsKeyReleased(ImGuiKey key);
    static long                    GetKeyPressedAmount(ImGuiKey key, float repeat_delay, float rate);
////    [Const] DOMString        GetKeyName(ImGuiKey key);
    static void                    SetNextFrameWantCaptureKeyboard(boolean want_capture_keyboard);

    static boolean                 IsMouseDown(long ImGuiMouseButton);
    static boolean                 IsMouseClicked(long ImGuiMouseButton, optional boolean repeat);
    static boolean                 IsMouseReleased(long ImGuiMouseButton);
    static boolean                 IsMouseDoubleClicked(long ImGuiMouseButton);
    static long                    GetMouseClickedCount(long ImGuiMouseButton);
    static boolean                 IsMouseHoveringRect([Const, Ref]ImVec2 r_min, [Const, Ref]ImVec2 r_max, optional boolean clip);
    static boolean                 IsMousePosValid([Const] optional ImVec2 mouse_pos);
    static boolean                 IsAnyMouseDown();
    [Value] static ImVec2          GetMousePos();
    [Value] static ImVec2          GetMousePosOnOpeningCurrentPopup();
    static boolean                 IsMouseDragging(long ImGuiMouseButton, optional float lock_threshold);
    [Value] static ImVec2          GetMouseDragDelta(optional long ImGuiMouseButton, optional float lock_threshold);
    static void                    ResetMouseDragDelta(optional long ImGuiMouseButton);
    static long                    GetMouseCursor();
    static void                    SetMouseCursor(long cursor_type);
    static void                    SetNextFrameWantCaptureMouse(boolean want_capture_mouse);

////    [Const] DOMString        GetClipboardText();
    static void                    SetClipboardText([Const] DOMString text);

    static void                    LoadIniSettingsFromDisk([Const] DOMString ini_filename);
    static void                    LoadIniSettingsFromMemory([Const] DOMString ini_data, optional long long ini_size);
    static void                    SaveIniSettingsToDisk([Const] DOMString ini_filename);
////    [Const] DOMString           SaveIniSettingsToMemory(optional long long[] out_ini_size); // ERROR
////    [Const] DOMString           SaveIniSettingsToMemory();
//
    static void                    DebugTextEncoding([Const] DOMString text);
    static boolean                 DebugCheckVersionAndDataLayout([Const] DOMString version_str, long long sz_io, long long sz_style, long long sz_vec2, long long sz_vec4, long long sz_drawvert, long long sz_drawidx); // This is called by IMGUI_CHECKVERSION() macro.
//
////    void                    SetAllocatorFunctions(ImGuiMemAllocFunc alloc_func, ImGuiMemFreeFunc free_func, optional any user_data);
////    void                    GetAllocatorFunctions(ImGuiMemAllocFunc* p_alloc_func, ImGuiMemFreeFunc* p_free_func, any* p_user_data);
//    static any                     MemAlloc(long long size);
//    static void                    MemFree(any ptr);
//
    [Ref] static ImGuiPlatformIO   GetPlatformIO();
    static void                    UpdatePlatformWindows();
    static void                    RenderPlatformWindowsDefault(optional any platform_render_arg, optional any renderer_render_arg);
    static void                    DestroyPlatformWindows();
    static ImGuiViewport           FindViewportByID(long id);
    static ImGuiViewport           FindViewportByPlatformHandle(any platform_handle);
};

//interface ImGuiSizeCallback {
//
//};
//
//[JSImplementation="ImGuiSizeCallback"]
//interface CustomImGuiSizeCallback {
//    void CustomImGuiSizeCallback();
//};

interface ImGuiInputTextCallbackData {
//    attribute byte[] Buf;
    attribute long BufSize;
    attribute boolean BufDirty;
    attribute long BufTextLen;
    attribute long Flags;
};

interface ImHelper {
    void memcpyIdx(long destination, ImDrawList drawList, long num);
    void memcpyVtx(long destination, ImDrawList drawList, long num);
    void memcpyFont(ImGuiIO io, long pixelBuffer, long[] widthData, long[] heightData, long[] bytesPerPixel);
    long getTextureId(ImDrawCmd imDrawCmd);
    void setIniFilename(ImGuiIO io, byte[] fileName);
    void removeIniFilename(ImGuiIO io);
    long getImGuiPayloadData(ImGuiPayload payload);
};

interface ImVec2 {
    attribute float x;
    attribute float y;

    void ImVec2();
    void ImVec2(float x, float y);
};

interface ImVec4 {
    attribute float x;
    attribute float y;
    attribute float z;
    attribute float w;

    void ImVec4();
    void ImVec4(float x, float y, float z, float w);

    [Operator="=", Ref] ImVec4 copy([Ref]ImVec4 value);
};

interface ImRect {
    void ImRect();
    void ImRect(float x1, float y1, float x2, float y2);
    [Value]attribute ImVec2 Min;
    [Value]attribute ImVec2 Max;

    [Value, Const] ImVec2 GetCenter();
    [Value, Const] ImVec2 GetSize();
    float GetWidth();
    float GetHeight();
    float GetArea();
//    ImVec2 GetTL() const
//    ImVec2 GetTR() const
//    ImVec2 GetBL() const
//    ImVec2 GetBR() const
};

interface VecCmdBuffer {
    [Operator="[]", Ref] ImDrawCmd getData(long index);
    long size();
};

interface VecIdxBuffer {
    long size();
};

interface VecVtxBuffer {
    long size();
};

interface ImVectorInt {
    [Operator="[]"] unsigned long getData(long index);
    long size();
    unsigned long front();
    unsigned long back();
};

interface ImDrawCmd {
    [Value]attribute ImVec4 ClipRect;
    attribute long VtxOffset;
    attribute long IdxOffset;
    attribute long ElemCount;
    attribute any TextureId;
};

interface ImDrawVert {
    [Value]attribute ImVec2 pos;
    [Value]attribute ImVec2 uv;
    attribute long col;
};

interface ImDrawData {
    attribute long CmdListsCount;
    attribute long TotalIdxCount;
    attribute long TotalVtxCount;
    attribute ImDrawList[] CmdLists;
    [Value]attribute ImVec2 DisplayPos;
    [Value]attribute ImVec2 DisplaySize;
    [Value]attribute ImVec2 FramebufferScale;
};

interface ImDrawList {
    [Value]attribute VecCmdBuffer CmdBuffer;
    [Value]attribute VecIdxBuffer IdxBuffer;
    [Value]attribute VecVtxBuffer VtxBuffer;

    void PushClipRect([Const, Ref] ImVec2 cr_min, [Const, Ref] ImVec2 cr_max, optional boolean intersect_with_current_clip_rect);
    void PushClipRectFullScreen();
    void PopClipRect();
    void PushTextureID(any user_texture_id);
    void PopTextureID();
    [Value] ImVec2 GetClipRectMin();
    [Value] ImVec2 GetClipRectMax();

    // Primitives
    void AddLine([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, long col, optional float thickness);
    void AddRect([Const, Ref] ImVec2 p_min, [Const, Ref] ImVec2 p_max, long col, optional float rounding, optional ImDrawFlags ImDrawFlags, float thickness);
    void AddRectFilled([Const, Ref] ImVec2 p_min, [Const, Ref] ImVec2 p_max, long col, optional float rounding, optional ImDrawFlags ImDrawFlags);
    void AddRectFilledMultiColor([Const, Ref] ImVec2 p_min, [Const, Ref] ImVec2 p_max, long col_upr_left, long col_upr_right, long col_bot_right, long col_bot_left);
    void AddQuad([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, [Const, Ref] ImVec2 p4, long col, optional float thickness);
    void AddQuadFilled([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, [Const, Ref] ImVec2 p4, long col);
    void AddTriangle([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, long col, optional float thickness);
    void AddTriangleFilled([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, long col);
    void AddCircle([Const, Ref] ImVec2 center, float radius, long col, optional long num_segments, optional float thickness);
    void AddCircleFilled([Const, Ref] ImVec2 center, float radius, long col, optional long num_segments);
    void AddNgon([Const, Ref] ImVec2 center, float radius, long col, long num_segments, optional float thickness);
    void AddNgonFilled([Const, Ref] ImVec2 center, float radius, long col, long num_segments);
    void AddEllipse([Const, Ref] ImVec2 center, [Const, Ref] ImVec2 radius, long col, optional float rot, optional long num_segments, optional float thickness);
    void AddEllipseFilled([Const, Ref] ImVec2 center, [Const, Ref] ImVec2 radius, long col, optional float rot, optional long num_segments);
    void AddText([Const, Ref] ImVec2 pos, long col, [Const] DOMString text_begin, [Const] optional DOMString text_end);
    void AddText([Const] ImFont font, float font_size, [Const, Ref] ImVec2 pos, long col, [Const] DOMString text_begin, [Const] optional DOMString text_end, optional float wrap_width, [Const] optional ImVec4 cpu_fine_clip_rect);
    void AddBezierCubic([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, [Const, Ref] ImVec2 p4, long col, float thickness, optional long num_segments);
    void AddBezierQuadratic([Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, long col, float thickness, optional long num_segments);

    // General polygon
//    void  AddPolyline([Const] ImVec2[] points, long num_points, long col, ImDrawFlags ImDrawFlags, float thickness);
//    void  AddConvexPolyFilled([Const] ImVec2[] points, long num_points, long col);
//    void  AddConcavePolyFilled([Const] ImVec2[] points, long num_points, long col);

    // Image primitives
    void AddImage(any user_texture_id, [Const, Ref] ImVec2 p_min, [Const, Ref] ImVec2 p_max, [Const, Ref] optional ImVec2 uv_min, [Const, Ref] optional ImVec2 uv_max, optional long col);
    void AddImageQuad(any user_texture_id, [Const, Ref] ImVec2 p1, [Const, Ref] ImVec2 p2, [Const, Ref] ImVec2 p3, [Const, Ref] ImVec2 p4, [Const, Ref] optional ImVec2 uv1, [Const, Ref] optional ImVec2 uv2, [Const, Ref] optional ImVec2 uv3, [Const, Ref] optional ImVec2 uv4, optional long col);
    void AddImageRounded(any user_texture_id, [Const, Ref] ImVec2 p_min, [Const, Ref] ImVec2 p_max, [Const, Ref] ImVec2 uv_min, [Const, Ref] ImVec2 uv_max, long col, float rounding, optional ImDrawFlags ImDrawFlags);

    void PathClear();
    void PathLineTo([Const, Ref] ImVec2 pos);
    void PathLineToMergeDuplicate([Const, Ref] ImVec2 pos);
    void PathFillConvex(long col);
    void PathStroke(long col, optional ImDrawFlags ImDrawFlags, optional float thickness);

    void ChannelsSplit(long count);
    void ChannelsMerge();
    void ChannelsSetCurrent(long n);
};

interface ImGuiIO {
    attribute boolean WantCaptureMouse;
    [Value]attribute ImVec2 DisplaySize;
    [Value]attribute ImVec2 DisplayFramebufferScale;
    attribute float DeltaTime;
    attribute ImFontAtlas Fonts;
    attribute float FontGlobalScale;
    attribute boolean ConfigDockingNoSplit;
    attribute boolean ConfigDockingWithShift;
    attribute boolean ConfigDockingAlwaysTabBar;
    attribute boolean ConfigDockingTransparentPayload;
    attribute long ConfigFlags;

    void AddMouseWheelEvent(float wheel_x, float wheel_y);
    void AddMouseButtonEvent(long button, boolean down);
    void AddMousePosEvent(float x, float y);
    void AddKeyEvent(ImGuiKey key, boolean down);
    void AddInputCharacter(unsigned long c);
};

interface ImFontAtlas {
    attribute any TexID;
};

interface ImFont {
    attribute float             FontSize;
};

interface ImGuiStyle {
    attribute float             Alpha;
    attribute float             DisabledAlpha;
    [Value] attribute ImVec2    WindowPadding;
    attribute float             WindowRounding;
    attribute float             WindowBorderSize;
    [Value] attribute ImVec2    WindowMinSize;
    [Value] attribute ImVec2    WindowTitleAlign;
    attribute long              WindowMenuButtonPosition;
    attribute float             ChildRounding;
    attribute float             ChildBorderSize;
    attribute float             PopupRounding;
    attribute float             PopupBorderSize;
    [Value] attribute ImVec2    FramePadding;
    attribute float             FrameRounding;
    attribute float             FrameBorderSize;
    [Value] attribute ImVec2    ItemSpacing;
    [Value] attribute ImVec2    ItemInnerSpacing;
    [Value] attribute ImVec2    CellPadding;
    [Value] attribute ImVec2    TouchExtraPadding;
    attribute float             IndentSpacing;
    attribute float             ColumnsMinSpacing;
    attribute float             ScrollbarSize;
    attribute float             ScrollbarRounding;
    attribute float             GrabMinSize;
    attribute float             GrabRounding;
    attribute float             LogSliderDeadzone;
    attribute float             TabRounding;
    attribute float             TabBorderSize;
    attribute float             TabMinWidthForCloseButton;
    attribute float             TabBarBorderSize;
    attribute long              ColorButtonPosition;
    [Value] attribute ImVec2    ButtonTextAlign;
    [Value] attribute ImVec2    SelectableTextAlign;
    attribute float             SeparatorTextBorderSize;
    [Value] attribute ImVec2    SeparatorTextAlign;
    [Value] attribute ImVec2    SeparatorTextPadding;
    [Value] attribute ImVec2    DisplayWindowPadding;
    [Value] attribute ImVec2    DisplaySafeAreaPadding;
    attribute float             DockingSeparatorSize;
    attribute float             MouseCursorScale;
    attribute boolean           AntiAliasedLines;
    attribute boolean           AntiAliasedLinesUseTex;
    attribute boolean           AntiAliasedFill;
    attribute float             CurveTessellationTol;
    attribute float             CircleTessellationMaxError;

    attribute float             HoverStationaryDelay;
    attribute float             HoverDelayShort;
    attribute float             HoverDelayNormal;
    attribute long              HoverFlagsForTooltipMouse;
    attribute long              HoverFlagsForTooltipNav;
    [Value] attribute ImVec4[]  Colors;

    void ScaleAllSizes(float scale_factor);
};

interface ImGuiViewport {
    attribute long ID;
    attribute long Flags;
    [Value] attribute ImVec2 Pos;
    [Value] attribute ImVec2 Size;
    [Value] attribute ImVec2 WorkPos;
    [Value] attribute ImVec2 WorkSize;
    attribute float DpiScale;
    attribute long ParentViewportId;
    attribute ImDrawData DrawData;
};

interface ImGuiTableSortSpecs {
};

interface ImGuiWindowClass {
};

[NoDelete]
interface ImGuiWindow {
    [Value] readonly attribute ImVectorInt IDStack;
    [Value] readonly attribute ImGuiWindowTempData DC;
    readonly attribute long ID;
    readonly attribute long Flags;
    readonly attribute long FlagsPreviousFrame;
    readonly attribute long ViewportId;
    [Value] attribute ImVec2 ViewportPos;
    attribute long ViewportAllowPlatformMonitorExtend;
    [Value] attribute ImVec2 Pos;
    [Value] attribute ImVec2 Size;
    [Value] attribute ImVec2 SizeFull;
    [Value] attribute ImVec2 ContentSize;
    [Value] attribute ImVec2 ContentSizeIdeal;
    [Value] attribute ImVec2 ContentSizeExplicit;
    [Value] attribute ImVec2 WindowPadding;
    attribute float WindowRounding;
    attribute float WindowBorderSize;
    attribute float DecoOuterSizeX1;
    attribute float DecoOuterSizeY1;
    attribute float DecoOuterSizeX2;
    attribute float DecoOuterSizeY2;
    attribute float DecoInnerSizeX1;
    attribute float DecoInnerSizeY1;
    attribute long NameBufLen;
    readonly attribute long MoveId;
    readonly attribute long TabId;
    readonly attribute long ChildId;
    [Value] attribute ImVec2 Scroll;
    [Value] attribute ImVec2 ScrollMax;
    [Value] attribute ImVec2 ScrollTarget;
    [Value] attribute ImVec2 ScrollTargetCenterRatio;
    [Value] attribute ImVec2 ScrollTargetEdgeSnapDist;
    [Value] attribute ImVec2 ScrollbarSizes;
    attribute boolean ScrollbarX;
    attribute boolean ScrollbarY;
    attribute boolean ViewportOwned;
    attribute boolean Active;
    attribute boolean WasActive;
    attribute boolean WriteAccessed;
    attribute boolean Collapsed;
    attribute boolean WantCollapseToggle;
    attribute boolean SkipItems;
    attribute boolean Appearing;
    attribute boolean Hidden;
    attribute boolean IsFallbackWindow;
    attribute boolean IsExplicitChild;
    attribute boolean HasCloseButton;

    [Value] attribute ImGuiStorage  StateStorage;

    attribute ImDrawList DrawList;

    attribute boolean DockIsActive;
    attribute boolean DockNodeIsVisible;
    attribute boolean DockTabIsVisible;
    attribute boolean DockTabWantClose;
    attribute ImGuiDockNode DockNode;
    attribute ImGuiDockNode DockNodeAsHost;
    attribute long DockId;
    attribute long DockTabItemStatusFlags;
    [Value] attribute ImRect DockTabItemRect;

    long GetID([Const] DOMString str);
//    long GetID(long n); // Method overloading issue
    long GetIDFromRectangle([Const, Ref] ImRect r_abs);

    [Const, Value] ImRect Rect();
    float CalcFontSize();
    float TitleBarHeight();
    [Const, Value] ImRect TitleBarRect();
    float MenuBarHeight();
    [Const, Value] ImRect MenuBarRect();
};

[NoDelete]
interface ImGuiWindowTempData {
    [Value] readonly attribute ImVec2 CursorPos;
    attribute long TreeDepth;
};

interface ImGuiPayload {
    attribute any Data;

    [Const] boolean IsPreview();
    [Const] boolean IsDelivery();
};

interface ImDrawListSharedData {
};

interface ImGuiStorage {
    void Clear();
    long GetInt(long key, optional long default_val);
    void SetInt(long key, long val);
    boolean GetBool(long key, optional boolean default_val);
    void SetBool(long key, boolean val);
    float GetFloat(long key, optional float default_val);
    void SetFloat(long key, float val);
};

interface ImGuiPlatformIO {
};

[NoDelete]
interface ImGuiContext {
    readonly attribute double Time;
    readonly attribute long NavId;

    // Windows state
    [Value] readonly attribute ImGuiStorage      WindowsById;
    readonly attribute long                      WindowsActiveCount;
    [Value] readonly attribute ImVec2            WindowsHoverPadding;
    readonly attribute long                      DebugBreakInWindow;
    readonly attribute ImGuiWindow               CurrentWindow;
    readonly attribute ImGuiWindow               HoveredWindow;
    readonly attribute ImGuiWindow               HoveredWindowUnderMovingWindow;
    readonly attribute ImGuiWindow               MovingWindow;
    readonly attribute ImGuiWindow               WheelingWindow;

    // Item/widgets state and tracking information
    readonly attribute long                      DebugHookIdInfo;
    readonly attribute long                      HoveredId;
    readonly attribute long                      HoveredIdPreviousFrame;
    readonly attribute boolean                   HoveredIdAllowOverlap;
    readonly attribute boolean                   HoveredIdDisabled;
    readonly attribute float                     HoveredIdTimer;
    readonly attribute float                     HoveredIdNotActiveTimer;
    readonly attribute long                      ActiveId;
    readonly attribute long                      ActiveIdIsAlive;
    readonly attribute float                     ActiveIdTimer;
    readonly attribute boolean                   ActiveIdIsJustActivated;
    readonly attribute boolean                   ActiveIdAllowOverlap;
    readonly attribute boolean                   ActiveIdNoClearOnFocusLoss;
    readonly attribute boolean                   ActiveIdHasBeenPressedBefore;
    readonly attribute boolean                   ActiveIdHasBeenEditedBefore;
    readonly attribute boolean                   ActiveIdHasBeenEditedThisFrame;
    readonly attribute boolean                   ActiveIdFromShortcut;
    readonly attribute long                      ActiveIdMouseButton;
    [Value] readonly attribute ImVec2            ActiveIdClickOffset;
    readonly attribute ImGuiWindow               ActiveIdWindow;
//    attribute long                      ActiveIdSource;
    readonly attribute long                      ActiveIdPreviousFrame;
    readonly attribute boolean                   ActiveIdPreviousFrameIsAlive;
    readonly attribute boolean                   ActiveIdPreviousFrameHasBeenEditedBefore;
    readonly attribute ImGuiWindow               ActiveIdPreviousFrameWindow;
    readonly attribute long                      LastActiveId;
    readonly attribute float                     LastActiveIdTimer;
};

interface ImGuiDockNode {
    attribute long LocalFlags;
    attribute long SelectedTabId;
    attribute ImGuiTabBar TabBar;
};

interface ImGuiTabBar {
    attribute long SelectedTabId;
    attribute long NextSelectedTabId;
};

interface ImGuiTabItem {
};

interface ImGuiShrinkWidthItem {
    attribute long Index;
    attribute float Width;
    attribute float InitialWidth;
};

enum ImGuiFocusedFlags {
    "ImGuiFocusedFlags_None",
    "ImGuiFocusedFlags_ChildWindows",
    "ImGuiFocusedFlags_RootWindow",
    "ImGuiFocusedFlags_AnyWindow",
    "ImGuiFocusedFlags_NoPopupHierarchy",
    "ImGuiFocusedFlags_DockHierarchy",
    "ImGuiFocusedFlags_RootAndChildWindows"
};

enum ImGuiConfigFlags {
    "ImGuiConfigFlags_None",
    "ImGuiConfigFlags_NavEnableKeyboard",
    "ImGuiConfigFlags_NavEnableGamepad",
    "ImGuiConfigFlags_NavEnableSetMousePos",
    "ImGuiConfigFlags_NavNoCaptureKeyboard",
    "ImGuiConfigFlags_NoMouse",
    "ImGuiConfigFlags_NoMouseCursorChange",
    "ImGuiConfigFlags_DockingEnable",
    "ImGuiConfigFlags_ViewportsEnable",
    "ImGuiConfigFlags_DpiEnableScaleViewports",
    "ImGuiConfigFlags_DpiEnableScaleFonts"
};

enum ImGuiKey {
    "ImGuiKey_None",
    "ImGuiKey_Tab",
    "ImGuiKey_LeftArrow",
    "ImGuiKey_RightArrow",
    "ImGuiKey_UpArrow",
    "ImGuiKey_DownArrow",
    "ImGuiKey_PageUp",
    "ImGuiKey_PageDown",
    "ImGuiKey_Home",
    "ImGuiKey_End",
    "ImGuiKey_Insert",
    "ImGuiKey_Delete",
    "ImGuiKey_Backspace",
    "ImGuiKey_Space",
    "ImGuiKey_Enter",
    "ImGuiKey_Escape",
    "ImGuiKey_LeftCtrl", "ImGuiKey_LeftShift", "ImGuiKey_LeftAlt", "ImGuiKey_LeftSuper",
    "ImGuiKey_RightCtrl", "ImGuiKey_RightShift", "ImGuiKey_RightAlt", "ImGuiKey_RightSuper",
    "ImGuiKey_Menu",
    "ImGuiKey_0", "ImGuiKey_1", "ImGuiKey_2", "ImGuiKey_3", "ImGuiKey_4", "ImGuiKey_5", "ImGuiKey_6", "ImGuiKey_7", "ImGuiKey_8", "ImGuiKey_9",
    "ImGuiKey_A", "ImGuiKey_B", "ImGuiKey_C", "ImGuiKey_D", "ImGuiKey_E", "ImGuiKey_F", "ImGuiKey_G", "ImGuiKey_H", "ImGuiKey_I", "ImGuiKey_J",
    "ImGuiKey_K", "ImGuiKey_L", "ImGuiKey_M", "ImGuiKey_N", "ImGuiKey_O", "ImGuiKey_P", "ImGuiKey_Q", "ImGuiKey_R", "ImGuiKey_S", "ImGuiKey_T",
    "ImGuiKey_U", "ImGuiKey_V", "ImGuiKey_W", "ImGuiKey_X", "ImGuiKey_Y", "ImGuiKey_Z",
    "ImGuiKey_F1", "ImGuiKey_F2", "ImGuiKey_F3", "ImGuiKey_F4", "ImGuiKey_F5", "ImGuiKey_F6",
    "ImGuiKey_F7", "ImGuiKey_F8", "ImGuiKey_F9", "ImGuiKey_F10", "ImGuiKey_F11", "ImGuiKey_F12",
    "ImGuiKey_Apostrophe",
    "ImGuiKey_Comma",
    "ImGuiKey_Minus",
    "ImGuiKey_Period",
    "ImGuiKey_Slash",
    "ImGuiKey_Semicolon",
    "ImGuiKey_Equal",
    "ImGuiKey_LeftBracket",
    "ImGuiKey_Backslash",
    "ImGuiKey_RightBracket",
    "ImGuiKey_GraveAccent",
    "ImGuiKey_CapsLock",
    "ImGuiKey_ScrollLock",
    "ImGuiKey_NumLock",
    "ImGuiKey_PrintScreen",
    "ImGuiKey_Pause",
    "ImGuiKey_Keypad0", "ImGuiKey_Keypad1", "ImGuiKey_Keypad2", "ImGuiKey_Keypad3", "ImGuiKey_Keypad4",
    "ImGuiKey_Keypad5", "ImGuiKey_Keypad6", "ImGuiKey_Keypad7", "ImGuiKey_Keypad8", "ImGuiKey_Keypad9",
    "ImGuiKey_KeypadDecimal",
    "ImGuiKey_KeypadDivide",
    "ImGuiKey_KeypadMultiply",
    "ImGuiKey_KeypadSubtract",
    "ImGuiKey_KeypadAdd",
    "ImGuiKey_KeypadEnter",
    "ImGuiKey_KeypadEqual",
    "ImGuiKey_GamepadStart",
    "ImGuiKey_GamepadBack",
    "ImGuiKey_GamepadFaceLeft",
    "ImGuiKey_GamepadFaceRight",
    "ImGuiKey_GamepadFaceUp",
    "ImGuiKey_GamepadFaceDown",
    "ImGuiKey_GamepadDpadLeft",
    "ImGuiKey_GamepadDpadRight",
    "ImGuiKey_GamepadDpadUp",
    "ImGuiKey_GamepadDpadDown",
    "ImGuiKey_GamepadL1",
    "ImGuiKey_GamepadR1",
    "ImGuiKey_GamepadL2",
    "ImGuiKey_GamepadR2",
    "ImGuiKey_GamepadL3",
    "ImGuiKey_GamepadR3",
    "ImGuiKey_GamepadLStickLeft",
    "ImGuiKey_GamepadLStickRight",
    "ImGuiKey_GamepadLStickUp",
    "ImGuiKey_GamepadLStickDown",
    "ImGuiKey_GamepadRStickLeft",
    "ImGuiKey_GamepadRStickRight",
    "ImGuiKey_GamepadRStickUp",
    "ImGuiKey_GamepadRStickDown",

    "ImGuiKey_MouseLeft", "ImGuiKey_MouseRight", "ImGuiKey_MouseMiddle", "ImGuiKey_MouseX1", "ImGuiKey_MouseX2", "ImGuiKey_MouseWheelX", "ImGuiKey_MouseWheelY",

    "ImGuiMod_None",
    "ImGuiMod_Ctrl",
    "ImGuiMod_Shift",
    "ImGuiMod_Alt",
    "ImGuiMod_Super",
    "ImGuiMod_Shortcut",
    "ImGuiMod_Mask_"
};

enum ImGuiColorEditFlags {
    "ImGuiColorEditFlags_None",
    "ImGuiColorEditFlags_NoAlpha",
    "ImGuiColorEditFlags_NoPicker",
    "ImGuiColorEditFlags_NoOptions",
    "ImGuiColorEditFlags_NoSmallPreview",
    "ImGuiColorEditFlags_NoTooltip",
    "ImGuiColorEditFlags_NoLabel",
    "ImGuiColorEditFlags_NoSidePreview",
    "ImGuiColorEditFlags_NoDragDrop",
    "ImGuiColorEditFlags_NoBorder",
    "ImGuiColorEditFlags_AlphaBar",
    "ImGuiColorEditFlags_AlphaPreview",
    "ImGuiColorEditFlags_AlphaPreviewHalf",
    "ImGuiColorEditFlags_HDR",
    "ImGuiColorEditFlags_DisplayRGB",
    "ImGuiColorEditFlags_DisplayHSV",
    "ImGuiColorEditFlags_DisplayHex",
    "ImGuiColorEditFlags_Uint8",
    "ImGuiColorEditFlags_Float",
    "ImGuiColorEditFlags_PickerHueBar",
    "ImGuiColorEditFlags_PickerHueWheel",
    "ImGuiColorEditFlags_InputRGB",
    "ImGuiColorEditFlags_InputHSV",
    "ImGuiColorEditFlags_DefaultOptions_"
};

enum ImGuiButtonFlags {
    "ImGuiButtonFlags_None",
    "ImGuiButtonFlags_MouseButtonLeft",
    "ImGuiButtonFlags_MouseButtonRight",
    "ImGuiButtonFlags_MouseButtonMiddle"
};

enum ImGuiTableColumnFlags {
    "ImGuiTableColumnFlags_None",
    "ImGuiTableColumnFlags_Disabled",
    "ImGuiTableColumnFlags_DefaultHide",
    "ImGuiTableColumnFlags_DefaultSort",
    "ImGuiTableColumnFlags_WidthStretch",
    "ImGuiTableColumnFlags_WidthFixed",
    "ImGuiTableColumnFlags_NoResize",
    "ImGuiTableColumnFlags_NoReorder",
    "ImGuiTableColumnFlags_NoHide",
    "ImGuiTableColumnFlags_NoClip",
    "ImGuiTableColumnFlags_NoSort",
    "ImGuiTableColumnFlags_NoSortAscending",
    "ImGuiTableColumnFlags_NoSortDescending",
    "ImGuiTableColumnFlags_NoHeaderLabel",
    "ImGuiTableColumnFlags_NoHeaderWidth",
    "ImGuiTableColumnFlags_PreferSortAscending",
    "ImGuiTableColumnFlags_PreferSortDescending",
    "ImGuiTableColumnFlags_IndentEnable",
    "ImGuiTableColumnFlags_IndentDisable",
    "ImGuiTableColumnFlags_IsEnabled",
    "ImGuiTableColumnFlags_IsVisible",
    "ImGuiTableColumnFlags_IsSorted",
    "ImGuiTableColumnFlags_IsHovered"
};

enum ImGuiComboFlags {
    "ImGuiComboFlags_None",
    "ImGuiComboFlags_PopupAlignLeft",
    "ImGuiComboFlags_HeightSmall",
    "ImGuiComboFlags_HeightRegular",
    "ImGuiComboFlags_HeightLarge",
    "ImGuiComboFlags_HeightLargest",
    "ImGuiComboFlags_NoArrowButton",
    "ImGuiComboFlags_NoPreview",
    "ImGuiComboFlags_HeightMask_"
};

enum ImGuiDir {
    "ImGuiDir_None",
    "ImGuiDir_Left",
    "ImGuiDir_Right",
    "ImGuiDir_Up",
    "ImGuiDir_Down"
};

enum ImGuiWindowFlags {
    "ImGuiWindowFlags_None",
    "ImGuiWindowFlags_NoTitleBar",
    "ImGuiWindowFlags_NoResize",
    "ImGuiWindowFlags_NoMove",
    "ImGuiWindowFlags_NoScrollbar",
    "ImGuiWindowFlags_NoScrollWithMouse",
    "ImGuiWindowFlags_NoCollapse",
    "ImGuiWindowFlags_AlwaysAutoResize",
    "ImGuiWindowFlags_NoBackground",
    "ImGuiWindowFlags_NoSavedSettings",
    "ImGuiWindowFlags_NoMouseInputs",
    "ImGuiWindowFlags_MenuBar",
    "ImGuiWindowFlags_HorizontalScrollbar",
    "ImGuiWindowFlags_NoFocusOnAppearing",
    "ImGuiWindowFlags_NoBringToFrontOnFocus",
    "ImGuiWindowFlags_AlwaysVerticalScrollbar",
    "ImGuiWindowFlags_AlwaysHorizontalScrollbar",
    "ImGuiWindowFlags_AlwaysUseWindowPadding",
    "ImGuiWindowFlags_NoNavInputs",
    "ImGuiWindowFlags_NoNavFocus",
    "ImGuiWindowFlags_UnsavedDocument",
    "ImGuiWindowFlags_NoDocking",
    "ImGuiWindowFlags_NoNav",
    "ImGuiWindowFlags_NoDecoration",
    "ImGuiWindowFlags_NoInputs"
};

enum ImGuiCond {
    "ImGuiCond_None",
    "ImGuiCond_Always",
    "ImGuiCond_Once",
    "ImGuiCond_FirstUseEver",
    "ImGuiCond_Appearing"
};

enum ImGuiSliderFlags {
    "ImGuiSliderFlags_None",
    "ImGuiSliderFlags_AlwaysClamp",
    "ImGuiSliderFlags_Logarithmic",
    "ImGuiSliderFlags_NoRoundToFormat",
    "ImGuiSliderFlags_NoInput"
};

enum ImGuiTabBarFlags {
    "ImGuiTabBarFlags_None",
    "ImGuiTabBarFlags_Reorderable",
    "ImGuiTabBarFlags_AutoSelectNewTabs",
    "ImGuiTabBarFlags_TabListPopupButton",
    "ImGuiTabBarFlags_NoCloseWithMiddleMouseButton",
    "ImGuiTabBarFlags_NoTabListScrollingButtons",
    "ImGuiTabBarFlags_NoTooltip",
    "ImGuiTabBarFlags_FittingPolicyResizeDown",
    "ImGuiTabBarFlags_FittingPolicyScroll",
    "ImGuiTabBarFlags_FittingPolicyMask_",
    "ImGuiTabBarFlags_FittingPolicyDefault_"
};

enum ImGuiTabItemFlags {
    "ImGuiTabItemFlags_None",
    "ImGuiTabItemFlags_UnsavedDocument",
    "ImGuiTabItemFlags_SetSelected",
    "ImGuiTabItemFlags_NoCloseWithMiddleMouseButton",
    "ImGuiTabItemFlags_NoPushId",
    "ImGuiTabItemFlags_NoTooltip",
    "ImGuiTabItemFlags_NoReorder",
    "ImGuiTabItemFlags_Leading",
    "ImGuiTabItemFlags_Trailing"
};

enum ImGuiDockNodeFlags {
    "ImGuiDockNodeFlags_None",
    "ImGuiDockNodeFlags_KeepAliveOnly",
    "ImGuiDockNodeFlags_NoDockingInCentralNode",
    "ImGuiDockNodeFlags_PassthruCentralNode",
    "ImGuiDockNodeFlags_NoSplit",
    "ImGuiDockNodeFlags_NoResize",
    "ImGuiDockNodeFlags_AutoHideTabBar"
};

enum ImGuiPopupFlags {
    "ImGuiPopupFlags_None",
    "ImGuiPopupFlags_MouseButtonLeft",
    "ImGuiPopupFlags_MouseButtonRight",
    "ImGuiPopupFlags_MouseButtonMiddle",
    "ImGuiPopupFlags_MouseButtonMask_",
    "ImGuiPopupFlags_MouseButtonDefault_",
    "ImGuiPopupFlags_NoOpenOverExistingPopup",
    "ImGuiPopupFlags_NoOpenOverItems",
    "ImGuiPopupFlags_AnyPopupId",
    "ImGuiPopupFlags_AnyPopupLevel",
    "ImGuiPopupFlags_AnyPopup"
};

enum ImGuiSelectableFlags {
    "ImGuiSelectableFlags_None",
    "ImGuiSelectableFlags_DontClosePopups",
    "ImGuiSelectableFlags_SpanAllColumns",
    "ImGuiSelectableFlags_AllowDoubleClick",
    "ImGuiSelectableFlags_Disabled",
    "ImGuiSelectableFlags_AllowOverlap"
};

enum ImGuiMouseButton {
    "ImGuiMouseButton_Left",
    "ImGuiMouseButton_Right",
    "ImGuiMouseButton_Middle"
};

enum ImGuiFocusRequestFlags {
    "ImGuiFocusRequestFlags_None",
    "ImGuiFocusRequestFlags_RestoreFocusedChild",
    "ImGuiFocusRequestFlags_UnlessBelowModal"
};

enum ImGuiInputSource {
    "ImGuiInputSource_None",
    "ImGuiInputSource_Mouse",
    "ImGuiInputSource_Keyboard",
    "ImGuiInputSource_Gamepad"
};

enum ImGuiChildFlags {
    "ImGuiChildFlags_None",
    "ImGuiChildFlags_Border",
    "ImGuiChildFlags_AlwaysUseWindowPadding",
    "ImGuiChildFlags_ResizeX",
    "ImGuiChildFlags_ResizeY",
    "ImGuiChildFlags_AutoResizeX",
    "ImGuiChildFlags_AutoResizeY",
    "ImGuiChildFlags_AlwaysAutoResize",
    "ImGuiChildFlags_FrameStyle"
};

enum ImDrawFlags {
    "ImDrawFlags_None",
    "ImDrawFlags_Closed",
    "ImDrawFlags_RoundCornersTopLeft",
    "ImDrawFlags_RoundCornersTopRight",
    "ImDrawFlags_RoundCornersBottomLeft",
    "ImDrawFlags_RoundCornersBottomRight",
    "ImDrawFlags_RoundCornersNone",
    "ImDrawFlags_RoundCornersTop",
    "ImDrawFlags_RoundCornersBottom",
    "ImDrawFlags_RoundCornersLeft",
    "ImDrawFlags_RoundCornersRight",
    "ImDrawFlags_RoundCornersAll",
    "ImDrawFlags_RoundCornersDefault_",
    "ImDrawFlags_RoundCornersMask_"
};

enum ImGuiItemFlags {
    "ImGuiItemFlags_None",
    "ImGuiItemFlags_NoTabStop",
    "ImGuiItemFlags_ButtonRepeat",
    "ImGuiItemFlags_Disabled",
    "ImGuiItemFlags_NoNav",
    "ImGuiItemFlags_NoNavDefaultFocus",
    "ImGuiItemFlags_SelectableDontClosePopup",
    "ImGuiItemFlags_MixedValue",
    "ImGuiItemFlags_ReadOnly",
    "ImGuiItemFlags_NoWindowHoverableCheck",
    "ImGuiItemFlags_AllowOverlap",
    "ImGuiItemFlags_Inputable",
    "ImGuiItemFlags_HasSelectionUserData"
};

enum ImGuiDragDropFlags {
    "ImGuiDragDropFlags_None",
    "ImGuiDragDropFlags_SourceNoPreviewTooltip",
    "ImGuiDragDropFlags_SourceNoDisableHover",
    "ImGuiDragDropFlags_SourceNoHoldToOpenOthers",
    "ImGuiDragDropFlags_SourceAllowNullID",
    "ImGuiDragDropFlags_SourceExtern",
    "ImGuiDragDropFlags_SourceAutoExpirePayload",
    "ImGuiDragDropFlags_AcceptBeforeDelivery",
    "ImGuiDragDropFlags_AcceptNoDrawDefaultRect",
    "ImGuiDragDropFlags_AcceptNoPreviewTooltip",
    "ImGuiDragDropFlags_AcceptPeekOnly"
};

enum ImGuiTreeNodeFlags {
    "ImGuiTreeNodeFlags_None",
    "ImGuiTreeNodeFlags_Selected",
    "ImGuiTreeNodeFlags_Framed",
    "ImGuiTreeNodeFlags_AllowOverlap",
    "ImGuiTreeNodeFlags_NoTreePushOnOpen",
    "ImGuiTreeNodeFlags_NoAutoOpenOnLog",
    "ImGuiTreeNodeFlags_DefaultOpen",
    "ImGuiTreeNodeFlags_OpenOnDoubleClick",
    "ImGuiTreeNodeFlags_OpenOnArrow",
    "ImGuiTreeNodeFlags_Leaf",
    "ImGuiTreeNodeFlags_Bullet",
    "ImGuiTreeNodeFlags_FramePadding",
    "ImGuiTreeNodeFlags_SpanAvailWidth",
    "ImGuiTreeNodeFlags_SpanFullWidth",
    "ImGuiTreeNodeFlags_NavLeftJumpsBackHere",
    "ImGuiTreeNodeFlags_CollapsingHeader"
};

enum ImGuiStyleVar {
    "ImGuiStyleVar_Alpha",
    "ImGuiStyleVar_DisabledAlpha",
    "ImGuiStyleVar_WindowPadding",
    "ImGuiStyleVar_WindowRounding",
    "ImGuiStyleVar_WindowBorderSize",
    "ImGuiStyleVar_WindowMinSize",
    "ImGuiStyleVar_WindowTitleAlign",
    "ImGuiStyleVar_ChildRounding",
    "ImGuiStyleVar_ChildBorderSize",
    "ImGuiStyleVar_PopupRounding",
    "ImGuiStyleVar_PopupBorderSize",
    "ImGuiStyleVar_FramePadding",
    "ImGuiStyleVar_FrameRounding",
    "ImGuiStyleVar_FrameBorderSize",
    "ImGuiStyleVar_ItemSpacing",
    "ImGuiStyleVar_ItemInnerSpacing",
    "ImGuiStyleVar_IndentSpacing",
    "ImGuiStyleVar_CellPadding",
    "ImGuiStyleVar_ScrollbarSize",
    "ImGuiStyleVar_ScrollbarRounding",
    "ImGuiStyleVar_GrabMinSize",
    "ImGuiStyleVar_GrabRounding",
    "ImGuiStyleVar_TabRounding",
    "ImGuiStyleVar_ButtonTextAlign",
    "ImGuiStyleVar_SelectableTextAlign",
    "ImGuiStyleVar_SeparatorTextBorderSize",
    "ImGuiStyleVar_SeparatorTextAlign",
    "ImGuiStyleVar_SeparatorTextPadding",
    "ImGuiStyleVar_DockingSeparatorSize"
};

enum ImGuiTableFlags {
    "ImGuiTableFlags_None",
    "ImGuiTableFlags_Resizable",
    "ImGuiTableFlags_Reorderable",
    "ImGuiTableFlags_Hideable",
    "ImGuiTableFlags_Sortable",
    "ImGuiTableFlags_NoSavedSettings",
    "ImGuiTableFlags_ContextMenuInBody",
    "ImGuiTableFlags_RowBg",
    "ImGuiTableFlags_BordersInnerH",
    "ImGuiTableFlags_BordersOuterH",
    "ImGuiTableFlags_BordersInnerV",
    "ImGuiTableFlags_BordersOuterV",
    "ImGuiTableFlags_BordersH",
    "ImGuiTableFlags_BordersV",
    "ImGuiTableFlags_BordersInner",
    "ImGuiTableFlags_BordersOuter",
    "ImGuiTableFlags_Borders",
    "ImGuiTableFlags_NoBordersInBody",
    "ImGuiTableFlags_NoBordersInBodyUntilResize",
    "ImGuiTableFlags_SizingFixedFit",
    "ImGuiTableFlags_SizingFixedSame",
    "ImGuiTableFlags_SizingStretchProp",
    "ImGuiTableFlags_SizingStretchSame",
    "ImGuiTableFlags_NoHostExtendX",
    "ImGuiTableFlags_NoHostExtendY",
    "ImGuiTableFlags_NoKeepColumnsVisible",
    "ImGuiTableFlags_PreciseWidths",
    "ImGuiTableFlags_NoClip",
    "ImGuiTableFlags_PadOuterX",
    "ImGuiTableFlags_NoPadOuterX",
    "ImGuiTableFlags_NoPadInnerX",
    "ImGuiTableFlags_ScrollX",
    "ImGuiTableFlags_ScrollY",
    "ImGuiTableFlags_SortMulti",
    "ImGuiTableFlags_SortTristate"
};

enum ImGuiHoveredFlags {
    "ImGuiHoveredFlags_None",
    "ImGuiHoveredFlags_ChildWindows",
    "ImGuiHoveredFlags_RootWindow",
    "ImGuiHoveredFlags_AnyWindow",
    "ImGuiHoveredFlags_NoPopupHierarchy",
    "ImGuiHoveredFlags_DockHierarchy",
    "ImGuiHoveredFlags_AllowWhenBlockedByPopup",
    "ImGuiHoveredFlags_AllowWhenBlockedByActiveItem",
    "ImGuiHoveredFlags_AllowWhenOverlappedByItem",
    "ImGuiHoveredFlags_AllowWhenOverlappedByWindow",
    "ImGuiHoveredFlags_AllowWhenDisabled",
    "ImGuiHoveredFlags_NoNavOverride",
    "ImGuiHoveredFlags_AllowWhenOverlapped",
    "ImGuiHoveredFlags_RectOnly",
    "ImGuiHoveredFlags_RootAndChildWindows",
    "ImGuiHoveredFlags_ForTooltip",
    "ImGuiHoveredFlags_Stationary",
    "ImGuiHoveredFlags_DelayNone",
    "ImGuiHoveredFlags_DelayShort",
    "ImGuiHoveredFlags_DelayNormal",
    "ImGuiHoveredFlags_NoSharedDelay"
};

enum ImGuiCol {
    "ImGuiCol_Text",
    "ImGuiCol_TextDisabled",
    "ImGuiCol_WindowBg",
    "ImGuiCol_ChildBg",
    "ImGuiCol_PopupBg",
    "ImGuiCol_Border",
    "ImGuiCol_BorderShadow",
    "ImGuiCol_FrameBg",
    "ImGuiCol_FrameBgHovered",
    "ImGuiCol_FrameBgActive",
    "ImGuiCol_TitleBg",
    "ImGuiCol_TitleBgActive",
    "ImGuiCol_TitleBgCollapsed",
    "ImGuiCol_MenuBarBg",
    "ImGuiCol_ScrollbarBg",
    "ImGuiCol_ScrollbarGrab",
    "ImGuiCol_ScrollbarGrabHovered",
    "ImGuiCol_ScrollbarGrabActive",
    "ImGuiCol_CheckMark",
    "ImGuiCol_SliderGrab",
    "ImGuiCol_SliderGrabActive",
    "ImGuiCol_Button",
    "ImGuiCol_ButtonHovered",
    "ImGuiCol_ButtonActive",
    "ImGuiCol_Header",
    "ImGuiCol_HeaderHovered",
    "ImGuiCol_HeaderActive",
    "ImGuiCol_Separator",
    "ImGuiCol_SeparatorHovered",
    "ImGuiCol_SeparatorActive",
    "ImGuiCol_ResizeGrip",
    "ImGuiCol_ResizeGripHovered",
    "ImGuiCol_ResizeGripActive",
    "ImGuiCol_Tab",
    "ImGuiCol_TabHovered",
    "ImGuiCol_TabActive",
    "ImGuiCol_TabUnfocused",
    "ImGuiCol_TabUnfocusedActive",
    "ImGuiCol_DockingPreview",
    "ImGuiCol_DockingEmptyBg",
    "ImGuiCol_PlotLines",
    "ImGuiCol_PlotLinesHovered",
    "ImGuiCol_PlotHistogram",
    "ImGuiCol_PlotHistogramHovered",
    "ImGuiCol_TableHeaderBg",
    "ImGuiCol_TableBorderStrong",
    "ImGuiCol_TableBorderLight",
    "ImGuiCol_TableRowBg",
    "ImGuiCol_TableRowBgAlt",
    "ImGuiCol_TextSelectedBg",
    "ImGuiCol_DragDropTarget",
    "ImGuiCol_NavHighlight",
    "ImGuiCol_NavWindowingHighlight",
    "ImGuiCol_NavWindowingDimBg",
    "ImGuiCol_ModalWindowDimBg"
};

enum ImGuiInputTextFlags {
    "ImGuiInputTextFlags_None",
    "ImGuiInputTextFlags_CharsDecimal",
    "ImGuiInputTextFlags_CharsHexadecimal",
    "ImGuiInputTextFlags_CharsUppercase",
    "ImGuiInputTextFlags_CharsNoBlank",
    "ImGuiInputTextFlags_AutoSelectAll",
    "ImGuiInputTextFlags_EnterReturnsTrue",
    "ImGuiInputTextFlags_CallbackCompletion",
    "ImGuiInputTextFlags_CallbackHistory",
    "ImGuiInputTextFlags_CallbackAlways",
    "ImGuiInputTextFlags_CallbackCharFilter",
    "ImGuiInputTextFlags_AllowTabInput",
    "ImGuiInputTextFlags_CtrlEnterForNewLine",
    "ImGuiInputTextFlags_NoHorizontalScroll",
    "ImGuiInputTextFlags_AlwaysOverwrite",
    "ImGuiInputTextFlags_ReadOnly",
    "ImGuiInputTextFlags_Password",
    "ImGuiInputTextFlags_NoUndoRedo",
    "ImGuiInputTextFlags_CharsScientific",
    "ImGuiInputTextFlags_CallbackResize",
    "ImGuiInputTextFlags_CallbackEdit",
    "ImGuiInputTextFlags_EscapeClearsAll"
};

// ImGui Internal

enum ImGuiAxis {
    "ImGuiAxis_None",
    "ImGuiAxis_X",
    "ImGuiAxis_Y"
};

enum ImGuiDataType {
    "ImGuiDataType_S8",
    "ImGuiDataType_U8",
    "ImGuiDataType_S16",
    "ImGuiDataType_U16",
    "ImGuiDataType_S32",
    "ImGuiDataType_U32",
    "ImGuiDataType_S64",
    "ImGuiDataType_U64",
    "ImGuiDataType_Float",
    "ImGuiDataType_Double"
};

enum ImGuiItemStatusFlags {
    "ImGuiItemStatusFlags_None",
    "ImGuiItemStatusFlags_HoveredRect",
    "ImGuiItemStatusFlags_HasDisplayRect",
    "ImGuiItemStatusFlags_Edited",
    "ImGuiItemStatusFlags_ToggledSelection",
    "ImGuiItemStatusFlags_ToggledOpen",
    "ImGuiItemStatusFlags_HasDeactivated",
    "ImGuiItemStatusFlags_Deactivated",
    "ImGuiItemStatusFlags_HoveredWindow",
    "ImGuiItemStatusFlags_Visible",
    "ImGuiItemStatusFlags_HasClipRect"
};