
interface ImLayout {
    static readonly attribute long WRAP_PARENT;
    static readonly attribute long MATCH_PARENT;
    static readonly attribute long MATCH_WRAP_PARENT;

    // Debug
    static void DrawBoundingBox_1(float x1, float y1, float x2, float y2, long r, long g, long b, optional long a, optional boolean clipping);
    static void DrawBoundingBox_2([Const, Ref] ImVec2 min, [Const, Ref] ImVec2 max, long r, long g, long b, optional long a, optional boolean clipping);
    static void DrawBoundingBox_3([Const, Ref] ImRect rect, long r, long g, long b, optional long a, optional boolean clipping);
    static void ShowLayoutDebug();
    static void ShowLayoutDebugClipping();

    // Layout
    static void BeginLayout_1(long id, float sizeX, float sizeY, [Const, Ref] optional ImGuiLayoutOptions options);
    static void BeginLayout_2([Const]DOMString id, float sizeX, float sizeY, [Const, Ref] optional ImGuiLayoutOptions options);
    static ImGuiLayout GetCurrentLayout();
    static void SetOrientation(ImOrientation ImOrientation);
    static void EndLayout();

    // Align view
    static void BeginAlign_1(long id, float sizeX, float sizeY, optional float alignX, optional float alignY, optional float offsetX, optional float offsetY, [Const, Ref] optional ImGuiLayoutOptions options);
    static void BeginAlign_2([Const]DOMString id, float sizeX, float sizeY, optional float alignX, optional float alignY, optional float offsetX, optional float offsetY, [Const, Ref] optional ImGuiLayoutOptions options);
    static void AlignLayout(float alignX, float alignY, optional float offsetX, optional float offsetY);
    static void EndAlign();

    // Custom Collapse Layout
    static boolean BeginCollapseLayout([Const]DOMString id, [Const]DOMString title, float sizeX, float sizeY);
    static boolean BeginCollapseLayout([Const]DOMString id, [Const]DOMString title, float sizeX, float sizeY, [Ref] ImGuiCollapseLayoutOptions option);
    static void BeginCollapseLayout_2([Const]DOMString id, boolean[] isOpen, [Const]DOMString title, float sizeX, float sizeY);
    static void BeginCollapseLayout_2([Const]DOMString id, boolean[] isOpen, [Const]DOMString title, float sizeX, float sizeY, [Ref] ImGuiCollapseLayoutOptions option);
    static void EndCollapseFrameLayout();
    static void EndCollapseLayout();
    static boolean BeginCollapseLayoutEx([Const]DOMString id, [Const]DOMString title, float sizeX, float sizeY);
    static boolean BeginCollapseLayoutEx([Const]DOMString id, [Const]DOMString title, float sizeX, float sizeY, [Ref] ImGuiCollapseLayoutOptions option);
    static boolean BeginCollapseLayoutEx_2(long id, [Const]DOMString title, float sizeX, float sizeY);
    static boolean BeginCollapseLayoutEx_2(long id, [Const]DOMString title, float sizeX, float sizeY, [Ref] ImGuiCollapseLayoutOptions option);
    static void BeginCollapseLayoutEx_3([Const]DOMString id, boolean[] isOpen, [Const]DOMString title, float sizeX, float sizeY);
    static void BeginCollapseLayoutEx_3([Const]DOMString id, boolean[] isOpen, [Const]DOMString title, float sizeX, float sizeY, [Ref] ImGuiCollapseLayoutOptions option);

    // Calculate content size
    static void BeginBoundingBox();
    [Ref] static ImRect EndBoundingBox();

    static float GetTableContentHeight();

    // Tree
    static void BeginGlobalTree();
    static void EndGlobalTree();
    static void BeginTree_1([Const]DOMString treeIdStr);
    static void BeginTree_2(long id);
    static void EndTree();
    static void BeginTreeLayout(float height, boolean isLeaf, boolean isSelected);
    static void BeginTreeLayout(float height, boolean isLeaf, boolean isSelected, boolean isOpen);
    static boolean EndTreeLayout();
    static boolean IsTreeOpen();
    static float GetTreeHeight(float padding);

    // Custom button behavior
    static long ButtonBehavior(long id, [Const, Ref]ImRect bb, boolean isSelected, optional long selectedColor, optional long hoveredColor, optional long hoveredStrokeColor, optional ImGuiButtonFlags ImGuiButtonFlags, optional float clickDelay);

    // Custom DPI Utils
    static void ScaleAllSizes(float scale_factor);
    static float GetDPIScale();
};

interface ImGuiLayoutOptions {
    void ImGuiLayoutOptions();
    attribute boolean clipping;
    attribute float paddingLeft;
    attribute float paddingRight;
    attribute float paddingTop;
    attribute float paddingBottom;
};

interface ImGuiCollapseLayoutOptions {
    void ImGuiCollapseLayoutOptions();
    attribute unsigned long arrowColor;
    attribute unsigned long arrowBackgroundHoveredColor;
    attribute unsigned long arrowBackgroundClickedColor;
    attribute unsigned long frameColor;
    attribute unsigned long borderColor;
    attribute long borderRound;
    attribute long roundingCorners;
    attribute boolean openDefault;
};
ImGuiCollapseLayoutOptions implements ImGuiLayoutOptions;

interface ImGuiLayout {
    [Value]attribute ImVec2 position;
    [Value]attribute ImVec2 size;

    [Value] ImVec2 getAbsoluteSize();
    [Value] ImVec2 getAbsoluteSizePadding();
    [Value] ImVec2 getContentSize();
    [Value] ImVec2 getPositionPadding();
};

enum ImOrientation {
    "NONE",
    "HORIZONTAL",
    "VERTICAL"
};