name: Deploy Libs

on:
    push:
      branches:
        - master
        - xpenatan-patch-1

jobs:
  build_Linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check Ant
      run: ant -version
    - name: Install mingw w64
      run: sudo apt-get install mingw-w64
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build classes
      run: ./gradlew build
    - name: Fetch imgui and generate native files
      run: ./gradlew generateNatives
    - name: Build Windows natives 
      run: ant -f ./jDear-imgui/jni/build-windows64.xml -Dhas-compiler=true -v
    - name: Build Linux natives 
      run: ant -f ./jDear-imgui/jni/build-linux64.xml -Dhas-compiler=true -v
    - name: Upload compiled natives
      uses: actions/upload-artifact@v1
      with:
        name: nativeFiles
        path: jDear-imgui/libs/
    