name: Deploy Libs

on:
    push:
      branches:
        - master
        - patch

jobs:
  build_Linux:
    name: Build Windows/Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check Ant
      run: ant -version
    - name: Install mingw w64
      run: sudo apt-get install mingw-w64
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Fetch imgui and generate imgui-cpp native files
      run: ./gradlew :imgui-cpp:generateNatives
    - name: Build imgui-cpp Windows natives 
      run: ant -f ./imgui-cpp/jni/build-windows64.xml -Dhas-compiler=true -v
    - name: Build imgui-cpp Linux natives 
      run: ant -f ./imgui-cpp/jni/build-linux64.xml -Dhas-compiler=true -v
      
    - name: Generate imgui-core native files
      run: ./gradlew :imgui-core:generateNatives
    - name: Build imgui-core Windows natives 
      run: ant -f ./imgui-core/jni/build-windows64.xml -Dhas-compiler=true -v
    - name: Build imgui-core Linux natives 
      run: ant -f ./imgui-core/jni/build-linux64.xml -Dhas-compiler=true -v
    - name: Upload compiled imgui-core natives
      uses: actions/upload-artifact@v1
      with:
        name: coreNativeFiles
        path: ./imgui-core/libs/
        
    - name: Generate imgui-layout native files
      run: ./gradlew :extensions:imgui-layout:generateNatives
    - name: Build imgui-layout Windows natives 
      run: ant -f ./extensions/imgui-layout/jni/build-windows64.xml -Dhas-compiler=true -v
    - name: Build imgui-layout Linux natives 
      run: ant -f ./extensions/imgui-layout/jni/build-linux64.xml -Dhas-compiler=true -v
    - name: Upload compiled imgui-layout natives
      uses: actions/upload-artifact@v1
      with:
        name: imlayoutNativeFiles
        path: ./extensions/imgui-layout/libs/

  build_Mac:
    name: Build Mac OS
    runs-on: macos-latest
    needs: build_Linux

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Ant
      run: brew install ant 
    - name: Download compiled natives
      uses: actions/download-artifact@v1
      with:
        name: coreNativeFiles
        path: ./imgui-core/libs/
    - name: Download compiled natives
      uses: actions/download-artifact@v1
      with:
        name: imlayoutNativeFiles
        path: ./extensions/imgui-layout/libs/
    - name: Check g++ version 
      run: gcc --version
    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Fetch imgui and generate imgui-cpp native files
      run: ./gradlew :imgui-cpp:generateNatives
    - name: Build imgui-cpp Mac OS X natives 
      run: ant -f ./imgui-cpp/jni/build-macosx64.xml -Dhas-compiler=true -v

    - name: Generate imgui-core native files
      run: ./gradlew :imgui-core:generateNatives
    - name: Build imgui-core Mac OS X natives 
      run: ant -f ./imgui-core/jni/build-macosx64.xml -Dhas-compiler=true -v
    - name: Pack natives to jar
      run: ant -f ./imgui-core/jni/build.xml pack-natives -v
    
    - name: Generate imgui-layout native files
      run: ./gradlew :extensions:imgui-layout:generateNatives
    - name: Build imgui-layout Mac OS X natives 
      run: ant -f ./extensions/imgui-layout/jni/build-macosx64.xml -Dhas-compiler=true -v
    - name: Pack natives to jar
      run: ant -f ./extensions/imgui-layout/jni/build.xml pack-natives -v
    - name: Upload to repository
      run: ./gradlew publish
      env:
        IMGUI_USER: ${{ secrets.IMGUI_USER }}
        IMGUI_PASSWORD: ${{ secrets.IMGUI_PASSWORD }}
    