name: Java CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  #  - name: Install Mingw
  #    run: sudo apt-get install g++-mingw-w64-i686 g++-mingw-w64-x86-64
    - name: Install Ant
      run: brew update brew install ant
    - name: check g++ version
      run: gcc --version
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew install
